account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'account'

urlpatterns = [
    # path('login/', views.user_login, name='user_login'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login2.html'), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(), name='user_logout'),
    path('register/', views.register, name='user_register'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change_form.html',
                                                                   success_url="/account/password_change_done/"),
         name='password_change'),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'),
         name='password_change_done'),
    path('my-information/', views.myself, name='my_information'),

]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<int:article_id>/', views.blog_article, name='blog_article'),

]

masite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    # path('', include('blog.urls')),  #todo: blog下面有两种路径可达。如何只是主页才跳转过来？
    path('account/', include('account.urls')),


]

account/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    birth = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=20, null=True)

    def __str__(self):
        return f'user {self.user.user_name}'


class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    school = models.CharField(max_length=100, blank=True)
    company = models.CharField(max_length=100, blank=True)
    profession = models.CharField(max_length=100, blank=True)
    address = models.CharField(max_length=100, blank=True)
    aboutme = models.TextField(blank=True)

    def __str__(self):
        return f'user: {self.user.username}'


class TempTable(models.Model):
    temp1 = models.CharField(max_length=100, blank=True)
    temp2 = models.OneToOneField(User, on_delete=models.CASCADE, blank=True)

blog/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User


class BlogArticles(models.Model):
    title = models.CharField(max_length=300)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ("-publish", )

    def __str__(self):
        return self.title

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile, UserInfo


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('passwords do not match.')
        return cd['password2']


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'birth')


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ('school', 'company', 'profession', 'address', 'aboutme')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', )

account/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm, RegisterForm, UserProfileForm
from django.contrib.auth.decorators import login_required
from .models import UserProfile, UserInfo
from django.contrib.auth.models import User


def user_login(request):
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user:
                login(request, user)
                return HttpResponse("Wellcome you . You have been authenticated successfully.")
            else:
                return HttpResponse('Sorry, Your username or password is not right.')
        else:
            return HttpResponse("Invalid login.")

    if request.method == 'GET':
        login_form = LoginForm()
        return render(request, 'account/login.html', {"form": login_form})


def register(request):
    if request.method == 'POST':
        user_form = RegisterForm(request.POST)
        userprofile_form = UserProfileForm(request.POST)
        if user_form.is_valid() & userprofile_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            new_profile = userprofile_form.save(commit=False)
            new_profile.user = new_user
            new_profile.save()
            return HttpResponse('successfully.')
        else:
            return HttpResponse('sorry, you cannot register.')
    else:
        user_form = RegisterForm()
        userprofile_form = UserProfileForm()
        return render(request, 'account/register.html', {'form': user_form, 'profile':userprofile_form})


@login_required()
def myself(request):
    userprofile = UserProfile.objects.get(user=request.user) if\
        hasattr(request.user, 'userprofile') else\
        UserProfile.objects.create(user=request.user)
    userinfo = UserInfo.objects.get(user=request.user) if \
        hasattr(request.user, 'userinfo') else\
        UserInfo.objects.create(user=request.user)

    return render(request, 'account/myself.html',
                  {
                      'user': request.user,
                      'userinfo': userinfo,
                      'userprofile': userprofile
                  })

blog/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from .models import BlogArticles


def blog_title(request):
    blogs = BlogArticles.objects.all()
    return render(request, "blog/titles.html", {'blogs': blogs})


def blog_article(request, article_id):
    # article = BlogArticles.objects.get(id=article_id)
    article = get_object_or_404(BlogArticles, id=article_id)
    pub = article.publish
    return render(request, 'blog/content.html', {'article':article, 'publish':pub})

templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="zh-cn">
<head>
    <meta charset="utf8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap-4.6/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-icons/bootstrap-icons.css' %}">

</head>

<body>
    {% include 'header.html' %}
    <div class="container">
        {% block content %}
        {% endblock content %}

    </div>
    {% include 'footer.html' %}

    {% block scripts %}
    <script src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.6/js/bootstrap.min.js' %}"></script>
    {% endblock scripts %}

</body>





</html>

templates/base01.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="https://github.com/necolas/normalize.css/blob/master/normalize.css">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>

</body>
</html>

templates/blog/content.html
{% extends 'base.html' %}

{% block title %}
blog content
{% endblock title %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>{{ article.title }}</h1>
</div>

<div class="row">
    <div class="col-xs-12 col-md-8">
        <p class="text-center">
            <span>{{ article.author.username }}</span>
            <span style="margin-left:20px">{{ publish }}</span>
        </p>
        <div>
            {{ article.body }}
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <h2>广告</h2>
        <p>跟老齐学：www.so.com</p>
    </div>
</div>
{% endblock content %}

templates/blog/titles.html
{% extends "base.html" %}
{% block title %}
blog titles
{% endblock title %}

{% block content %}
    <div class="row text-center vertical-middle-sm">
        <h1>我的博客</h1>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <ul>
                {% for blog in blogs %}
                <li>
                    <a href="{% url 'blog:blog_article' blog.id %}">{{ blog.title }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>

        <div class="col-ks-6 col-md-4">
            <h2>广告</h2>
            <p>跟老齐学：www.so.com</p>
        </div>
    </div>

{% endblock content %}

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right of angelyhch study qiwser</p>
</div>

templates/header.html
{% load static %}

<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a href="https://www.so.com/" class="navbar-brand">
                <i class="bi bi-house"></i>360搜索主页
            </a>
        </div>

        <div>
            <ul class="nav navbar-nav " role="navigation">
                <li>
                    <a href="{% url 'blog:blog_title' %}">BLOG</a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <div class="dropdown" style="margin-top:8px">
                    <button class="btn-btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown">
                        {{ user.username }}
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'account:password_change' %}">
                                修改密码
                            </a>
                        </li>
                    </ul>
                </div>

                <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

</div>